apiVersion: v1
kind: Service
metadata:
  name: go-service-svc
  namespace: mumnk8s
spec:
  selector:
    app: go-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
